[package]
name = "openbabel"
version = "0.1.0"
edition = "2018"
authors = ["Qin Wan <rogerwq@gmail.com>"]
license = "MIT"
repository = "https://github.com/rogerwq/openbabel-rust"
homepage = "https://github.com/rogerwq/openbabel-rust"
documentation = "https://docs.rs/openbabel"
keywords = ["cheminformatics", "openbabel"]
categories = ["science"]

[dependencies]
openbabel-sys = { path = "openbabel-sys", version = "0.1.0" }
cxx = "1.0"