[package]
name = "openbabel"
version = "0.1.0"
edition = "2018"
authors = ["Qin Wan <rogerwq@gmail.com>"]
license = "MIT"

[dependencies]
openbabel-sys = { path = "openbabel-sys", version = "0.1.0" }
cxx = "1.0"